YUNIKORN-746: Simplify the REST API document
apache/incubator-yunikorn-site pull request #64
Opened 2021-07-17 03:08 UTC by manirajv06

Doc changes to clearly explain the Old and Newer version API's use.

2021-07-17 03:49 UTC, yangwwei commented
hi @manirajv06  thanks for working on this. Can we remove the "Deprecated" and "Newer version" in the doc, and merge them into one section? For queus/apps/nodes, we should only have one section each, and the old/new API can all be explained in each single section.

2021-07-18 15:01 UTC, manirajv06 commented
Taken care. Pls check.

2021-07-18 19:44 UTC, yangwwei requested changes
Thanks, it looks much better. I just added some minor comments to request the change of sub-titles, hope that makes sense.

2021-07-18 19:44 UTC, yangwwei commented on docs/api/scheduler.md
> +### Single Partition
Partition queues

2021-07-18 19:44 UTC, yangwwei commented on docs/api/scheduler.md
> +### All Partitions
All queues

2021-07-18 19:44 UTC, yangwwei commented on docs/api/scheduler.md
> +### Single Partition
Queue applications

2021-07-18 19:44 UTC, yangwwei commented on docs/api/scheduler.md
> +### All Partitions
All applications

2021-07-18 19:44 UTC, yangwwei commented on docs/api/scheduler.md
> +### Single Partition
Partition nodes

2021-07-18 19:44 UTC, yangwwei commented on docs/api/scheduler.md
> +### All Partitions
All nodes

2021-07-19 05:35 UTC, yangwwei approved these changes
LGTM

2021-07-19 05:35 UTC, merged